In [1]:
# 19.06.27 Thu
# 1. Roughly Cutted out Datas
# 2. Roughly trained them with "My" Model
# 
# To do From now on
# - improve accuracy with "My" Model, editing some codes little by little,
#   need to study more...
# - study more about data truncating
# - how should we deal with Categorical Datas? Will gender, ticket-class have any tendency?
#   need to see covariance between them
import numpy as np
import pandas as pd

# calling data by pandas
# passenger id, no needed...
data_ = pd.read_csv("train.csv", index_col=0)
data_.head(4)

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S

In [2]:
# Guess Ticket would work but doesn't seem to work nicely
# Fare and Cabin and Embarked ... not much relevance
# let's take Pclass, Age, SibSp, Parch and Fare for now
data_['Ticket'].value_counts()

1601                 7
347082               7
CA. 2343             7
3101295              6
CA 2144              6
347088               6
382652               5
S.O.C. 14879         5
4133                 4
349909               4
2666                 4
113760               4
19950                4
W./C. 6608           4
113781               4
LINE                 4
PC 17757             4
17421                4
347077               4
230080               3
24160                3
35273                3
110152               3
PC 17760             3
110413               3
PC 17755             3
C.A. 34651           3
347742               3
345773               3
371110               3
                    ..
5727                 1
347060               1
234604               1
239854               1
SOTON/OQ 392090      1
SC/PARIS 2167        1
111240               1
3101264              1
349246               1
392092               1
3101281              1
350036               1
343120     

In [3]:
data_['Fare'].value_counts()

8.0500      43
13.0000     42
7.8958      38
7.7500      34
26.0000     31
10.5000     24
7.9250      18
7.7750      16
26.5500     15
0.0000      15
7.2292      15
7.8542      13
8.6625      13
7.2500      13
7.2250      12
16.1000      9
9.5000       9
24.1500      8
15.5000      8
56.4958      7
52.0000      7
14.5000      7
14.4542      7
69.5500      7
7.0500       7
31.2750      7
46.9000      6
30.0000      6
7.7958       6
39.6875      6
            ..
7.1417       1
42.4000      1
211.5000     1
12.2750      1
61.1750      1
8.4333       1
51.4792      1
7.8875       1
8.6833       1
7.5208       1
34.6542      1
28.7125      1
25.5875      1
7.7292       1
12.2875      1
8.6542       1
8.7125       1
61.3792      1
6.9500       1
9.8417       1
8.3000       1
13.7917      1
9.4750       1
13.4167      1
26.3875      1
8.4583       1
9.8375       1
8.3625       1
14.1083      1
17.4000      1
Name: Fare, Length: 248, dtype: int64

In [4]:
data_['Cabin'].value_counts()

C23 C25 C27    4
G6             4
B96 B98        4
F33            3
F2             3
C22 C26        3
D              3
E101           3
F G73          2
B49            2
B28            2
E67            2
D33            2
B5             2
C124           2
B20            2
C126           2
B51 B53 B55    2
E121           2
E44            2
C68            2
E33            2
D35            2
B18            2
C65            2
E8             2
C92            2
B58 B60        2
E24            2
E25            2
              ..
B50            1
C106           1
B86            1
D49            1
B78            1
E77            1
E50            1
E36            1
C91            1
D50            1
C7             1
A16            1
A26            1
E10            1
B79            1
A5             1
B39            1
A36            1
B41            1
B71            1
C87            1
E58            1
C111           1
D15            1
A10            1
B69            1
D11            1
E49           

In [5]:
# name... would not affect to sb's survival at all...
# sex may be relevant due to some physical
# Siblings and Spouses might affect because it would either help them survive or the opposite
# Parents and Children would samely affect from SibSp
data_[['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 5 columns):
Pclass    891 non-null int64
Age       714 non-null float64
SibSp     891 non-null int64
Parch     891 non-null int64
Fare      891 non-null float64
dtypes: float64(2), int64(3)
memory usage: 41.8 KB


In [6]:
# but 'age' doesn't have full data
# we need to interpolate them in some way
feature = np.array(data_[['Pclass', 'SibSp', 'Parch', 'Fare']])
target = np.array(data_['Survived'])

In [7]:
from data_analysis.main import *
from data_analysis.loss_function import *
from data_analysis.optimizer import *

In [8]:
model_sgd = Model(feature, target, LogLikelihood)
model_mom = Model(feature, target, LogLikelihood)
model_adam = Model(feature, target, LogLikelihood)

There are 4 options of optimizers
1. Normal Stochastic Gradient
2. Momentum SGD
3. AdaGrad SGD
4. Adam(combination of Momentum SGD and AdaGrad)
5. Nesterov
Type in the number of what to optimize : 1
There are 4 options of optimizers
1. Normal Stochastic Gradient
2. Momentum SGD
3. AdaGrad SGD
4. Adam(combination of Momentum SGD and AdaGrad)
5. Nesterov
Type in the number of what to optimize : 2
There are 4 options of optimizers
1. Normal Stochastic Gradient
2. Momentum SGD
3. AdaGrad SGD
4. Adam(combination of Momentum SGD and AdaGrad)
5. Nesterov
Type in the number of what to optimize : 4


In [9]:
model_sgd.beta

array([-0.16925139,  0.99161714, -0.8906637 ,  0.11141137,  1.3886144 ])

In [10]:
# to see how they learn well, set all three same
model_mom.beta = model_sgd.beta.copy()
model_adam.beta = model_sgd.beta.copy()

In [11]:
# absolutely they should value the same
model_sgd.loss_function.accuracy(model_sgd.beta)
model_mom.loss_function.accuracy(model_mom.beta)
model_adam.loss_function.accuracy(model_adam.beta)

38.38383838383838
38.38383838383838
38.38383838383838


38.38383838383838

In [12]:
print("SGD")
print(model_sgd.beta)
model_sgd.train()
print(model_sgd.beta)
print("\n")

print("Momentum")
print(model_mom.beta)
model_mom.train()
print(model_mom.beta)
print("\n")

print("AdaM")
print(model_adam.beta)
model_adam.train()
print(model_adam.beta)
print("\n")

SGD
[-0.16925139  0.99161714 -0.8906637   0.11141137  1.3886144 ]
38.38383838383838
68.79910213243546
[-0.13297167 -0.43834208 -0.50449504  0.24989341  0.04020526]


Momentum
[-0.16925139  0.99161714 -0.8906637   0.11141137  1.3886144 ]
38.38383838383838
61.61616161616161
[-4.35396624  0.86740129 -1.05195298  0.39548509 -4.06723847]


AdaM
[-0.16925139  0.99161714 -0.8906637   0.11141137  1.3886144 ]
38.38383838383838
59.82042648709316
[ 0.35837845 -0.51486537 -0.20960528  0.29187617  0.12860893]




In [13]:
# all for today
# tomorrow
# - truncate age, which is really important
# - 1. interpolate 'nan' datas
# - 2. or just delete the whole 'nan'
#
# - How should we deal with categorical datas - 'Pclass', 'Sex'