In [ ]:
import numpy as np
layer_structure = [5, 6, 2]
weights = {i: np.random.rand(element, layer_structure[i+1]) for i, element in enumerate(layer_structure[:-1])}
weights[0].shape

In [77]:
import csv
from data_analysis.loss_function import *
from data_analysis.main import *
from data_analysis.optimizer import *

data_ = csv.reader(open("train.csv"))
header = data_.__next__()
data = list(data_)
target = [float(d[1]) for d in data]

In [22]:
def filter_str_to_float(x):
    try:
        return float(x)
    except ValueError:
        return x

In [37]:
data_wo_str = [[filter_str_to_float(d) for  d in line[2:]] for line in data]

In [38]:
data_wo_str[0]

[3.0,
 'Braund, Mr. Owen Harris',
 'male',
 22.0,
 1.0,
 0.0,
 'A/5 21171',
 7.25,
 '',
 'S']

In [26]:
print(header)

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']


In [39]:
def sex_to_float(gender):
    if gender=='male':
        return 0
    elif gender=='female':
        return 1
    else:
        return -1

In [40]:
data_gender = data_wo_str[:]

In [43]:
import pandas as pd

In [48]:
data_pd = pd.read_csv('train.csv', index_col=0)
data_pd.tail(10)

Survived  Pclass                                      Name  \
PassengerId                                                               
882                 0       3                        Markun, Mr. Johann   
883                 0       3              Dahlberg, Miss. Gerda Ulrika   
884                 0       2             Banfield, Mr. Frederick James   
885                 0       3                    Sutehall, Mr. Henry Jr   
886                 0       3      Rice, Mrs. William (Margaret Norton)   
887                 0       2                     Montvila, Rev. Juozas   
888                 1       1              Graham, Miss. Margaret Edith   
889                 0       3  Johnston, Miss. Catherine Helen "Carrie"   
890                 1       1                     Behr, Mr. Karl Howell   
891                 0       3                       Dooley, Mr. Patrick   

                Sex   Age  SibSp  Parch            Ticket     Fare Cabin  \
PassengerId                                                                
882            male  33.0      0      0            349257   7.8958   NaN   
883          female  22.0      0      0              7552  10.5167   NaN   
884            male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN   
885            male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN   
886          female  39.0      0      5            382652  29.1250   NaN   
887            male  27.0      0      0            211536  13.0000   NaN   
888          female  19.0      0      0            112053  30.0000   B42   
889          female   NaN      1      2        W./C. 6607  23.4500   NaN   
890            male  26.0      0      0            111369  30.0000  C148   
891            male  32.0      0      0            370376   7.7500   NaN   

            Embarked  
PassengerId           
882                S  
883                S  
884                S  
885                S  
886                Q  
887                S  
888                S  
889                S  
890                C  
891                Q

In [73]:
import numpy as np
from data_analysis.main import *
from data_analysis.loss_function import *
from data_analysis.optimizer import *

In [72]:
usable = np.array(data_pd[['Pclass', 'SibSp', 'Parch', 'Fare']])
usable

array([[ 3.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    ,  0.    , 71.2833],
       [ 3.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 3.    ,  1.    ,  2.    , 23.45  ],
       [ 1.    ,  0.    ,  0.    , 30.    ],
       [ 3.    ,  0.    ,  0.    ,  7.75  ]])

In [78]:
obj = Model(usable, target, LogLikelihood)

There are 4 options of optimizers
1. Normal Stochastic Gradient
2. Momentum SGD
3. AdaGrad SGD
4. Adam(combination of Momentum SGD and AdaGrad)
5. Nesterov
Type in the number of what to optimize : 1


In [83]:
obj.train()

624
620


In [82]:
obj.beta

array([ 0.05066075, -0.49048698, -0.43164617,  0.24557868,  0.05744542])

In [84]:
momentum = Model(usable, target, LogLikelihood)

There are 4 options of optimizers
1. Normal Stochastic Gradient
2. Momentum SGD
3. AdaGrad SGD
4. Adam(combination of Momentum SGD and AdaGrad)
5. Nesterov
Type in the number of what to optimize : 4


In [85]:
momentum.beta

array([ 0.79570203,  0.15019867,  0.15842086, -0.72789948,  0.16126525])

In [86]:
momentum.train()

342
549


In [87]:
momentum.beta

array([ 0.37969487, -0.52275596, -0.24729587,  0.29572181, -0.00611119])

In [88]:
momentum.train()

549
615


In [89]:
momentum.beta

array([ 0.3822054 , -0.54965104, -0.16453177,  0.286744  ,  0.02929011])

In [90]:
momentum.train()

615
613


In [91]:
momentum.beta = np.array([ 0.3822054 , -0.54965104, -0.16453177,  0.286744  ,  0.02929011])

In [93]:
momentum.loss_function.accuracy(momentum.beta)

615


69.02356902356902

In [71]:
data_pd.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 11 columns):
Survived    891 non-null int64
Pclass      891 non-null int64
Name        891 non-null object
Sex         891 non-null object
Age         714 non-null float64
SibSp       891 non-null int64
Parch       891 non-null int64
Ticket      891 non-null object
Fare        891 non-null float64
Cabin       204 non-null object
Embarked    889 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 123.5+ KB


In [95]:
data_pd['Ticket'].value_counts()

1601                7
CA. 2343            7
347082              7
347088              6
3101295             6
CA 2144             6
382652              5
S.O.C. 14879        5
4133                4
19950               4
2666                4
113781              4
347077              4
349909              4
LINE                4
PC 17757            4
17421               4
113760              4
W./C. 6608          4
PC 17572            3
110413              3
C.A. 31921          3
SC/Paris 2123       3
347742              3
363291              3
F.C.C. 13529        3
345773              3
35273               3
371110              3
230080              3
                   ..
11755               1
363294              1
36864               1
113043              1
C 17369             1
230434              1
347073              1
244373              1
A/5 3902            1
347074              1
6563                1
248723              1
349210              1
349207              1
345783    